routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [\App\Http\Controllers\PostController::class, 'list'])->name('posts');
Route::get('posts/{post}', [\App\Http\Controllers\PostController::class, 'show'])->name('posts.show');

Auth::routes(['verify' => true]);


Route::group(['middleware' => ['verified', 'auth'] ], function (    ) {
    Route::get('/home', 'HomeController@index')->name('home');
    Route::resource('users/{id}/posts',    'PostController')->except('show');
    Route::resource('users/{id}posts/{post}/comments',    'CommentController')->only(['update', 'store']);
});

app/Models/Post.php
<?php

namespace App\Models;

use App\Services\UploadService;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\Relation;

class Post extends Model
{
    /**
     * @var string[]
     */
    protected $fillable = [
      'user_id',
      'name',
      'description',
      'image',
    ];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function comments(): Relation
    {
        return $this->hasMany(Comment::class);
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function author(): Relation
    {
        return $this->belongsTo(User::class);
    }

    /**
     * @return string
     */
    public function getImgPathAttribute() : string
    {
        return $this->image ? "/storage/$this->image" : asset('images/default_user.png');
    }

    /**
     * @param null $image
     */
    public function deleteExistingImg($image = null ): void
    {
        $image = $image ?? $this->image;

        if($image) {
            (new UploadService())->delete($image);
        }
    }

    /**
     * Delete old images  from storage
     */
    protected static function boot() {
        parent::boot();

        static::deleted(function($post) {
            $post->deleteExistingImg();
        });

        static::updating(function($post) {
            $path =   $post->getOriginal('image');
            $post->deleteExistingImg($path);
        });
    }

}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\Post\PostCreateRequest;
use App\Http\Requests\Post\PostUpdateRequest;
use App\Interfaces\PostInterface;
use App\Models\Post;
use App\Services\UploadService;
use Illuminate\Http\Request;

class PostController extends Controller
{
    /**
     * PostController constructor.
     * @param PostInterface $repository
     */
    public function __construct(PostInterface $repository)
    {
        $this->repository = $repository;
    }

    /**
     * @param Request $request
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function list(Request $request)
    {
        $posts = $this->repository->get();

        if($request->ajax()) {
            return view('components.posts', compact('posts'));
        }

        return view('index', compact('posts'));
    }



    /**
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index()
    {
        $posts = $this->repository->userPosts();

        return view('posts.index', compact('posts'));
    }

    /**
     * @param $userId
     * @param Request $request
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function create($userId, Request $request)
    {
        return view('posts.create');
    }

    /**
     * @param int $userId
     * @param PostCreateRequest $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store( int $userId, PostCreateRequest $request)
    {
        $form = $request->only(['name', 'description', 'image']);
        $this->repository->store($form);

        return redirect()->route('posts.index', $request->user())->with(['success' => "Post Created"]);
    }


    /**
     * @param $userId
     * @param Request $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function edit(int $userId, Post $post, Request $request)
    {
        $this->repository->edit($post);

        return view('posts.edit' , compact('post'));
    }

    /**
     * @param Post $post
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function show(Post $post)
    {
        $post->load('comments.comentor:name,id');

        return view('posts.show' , compact('post'));
    }

    /**
     * @param $id
     * @param Post $post
     * @param PostUpdateRequest $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(int $id, Post $post, PostUpdateRequest $request)
    {
        $this->repository->update($post, $request->only(['name', 'description', 'image']));

        return redirect()->route('posts.index', $request->user())->with(['success' => "Post Updated"]);
    }

    /**
     * @param $userId
     * @param Request $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function destroy(int $userId, Post $post, Request $request)
    {
        $post->delete();

        return redirect()->route('posts.index', $request->user())->with(['success' => "Post deleted"]);
    }
}

resources/views/posts/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="col-12">


        <div class="row justify-content-between mb-4">
            <div    class="h3 col-6">    Posts create</div>

            <div    class="col-2">
                <a href="{{route('posts.index', auth()->id())}}" class="btn btn-primary"> Back</a>

            </div>
{{--            @include('components/messages')--}}
        </div>


        <form method="POST" enctype="multipart/form-data" action="{{route('posts.store', auth()->id())}}">
            @csrf
            <div class="form-group">
                <label for="exampleFormControlInput1">Name</label>
                <input type="text" class="form-control" id="exampleFormControlInput1" name="name">
            </div>

            <div class="form-group">
                <label for="exampleFormControlTextarea1">Description</label>
                <textarea class="form-control" id="exampleFormControlTextarea1" rows="3" name="description"></textarea>
            </div>
            <div class="form-group">
                <label for="exampleFormControlFile1">Post image</label>
                <input type="file" class="form-control-file" id="exampleFormControlFile1" name="image">
            </div>
            <div class="form-group clearfix">

                <button type="submit" class="btn btn-primary float-right">
                    Create
                </button>
            </div>

        </form>
    </div>
@endsection

resources/views/posts/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="col-12">


        <div class="row justify-content-between mb-4">
            <div    class="h3 col-6">    Posts edit </div>

            <div    class="col-2">
                <a href="{{route('posts.index', auth()->id())}}" class="btn btn-primary"> Back</a>

            </div>
{{--            @include('components/messages')--}}
        </div>


        <form method="POST" enctype="multipart/form-data" action="{{route('posts.update', [ auth()->id(), $post->id])}}">
            @csrf
            @method('PUT')
            <div class="form-group">
                <label for="exampleFormControlInput1">Name</label>
                <input type="text" class="form-control" id="exampleFormControlInput1" name="name" value="{{$post->name}}">
            </div>

            <div class="form-group">
                <label for="exampleFormControlTextarea1">Description</label>
                <textarea class="form-control"  rows="3" name="description"> {{$post->description}} </textarea>
            </div>
            <div class="form-group">
                <label for="exampleFormControlFile1">Post image</label>
                <input type="file" class="form-control-file" id="exampleFormControlFile1" name="image" >
            </div>
            <div >
                <img src="{{$post->img_path}}" alt="" width="800">
            </div>
            <div class="form-group clearfix">

                <button type="submit" class="btn btn-primary float-right">
                    Update
                </button>
            </div>

        </form>
    </div>
@endsection

resources/views/posts/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="col-12 mb-4">

        <div class="row justify-content-between">
            <div class="h3 col-6"> Posts</div>
            <div class="col-2">
                <a href="{{route('posts.create', auth()->id())}}" class="btn btn-primary">Create</a>
            </div>
            @include('components/messages')

        </div>

    </div>


    <table class="table">

        <caption>List of users</caption>
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Name</th>
            <th scope="col">Logo</th>
            <th scope="col">Actions</th>

        </tr>
        </thead>
        <tbody>
        @php
            $userId = auth()->id()
        @endphp
        @foreach($posts as $key =>  $post)
            <tr>
                <th scope="row">{{$key}}</th>
                <td>{{$post->name}}</td>
                <td><img src="{{$post->img_path}}" alt="" class="img-fluid" width="60px;"></td>
                <td>
                    <a href="{{route('posts.edit',[$userId, $post->id])}}" class="btn-link"> <i class="fas fa-edit"></i>
                    </a>
                    <a href="{{route('posts.show', $post->id)}}" class="btn-link ml-1"> <i class="far fa-eye"></i> </a>
                    <form action="{{route('posts.destroy',[$userId, $post->id])}}" class="d-inline-block" method="POST">
                        @csrf
                        @method('delete')
                        <button type="submit" class="btn-link ml-1" style="border: none; background: none"> <i class="fas fa-trash"></i>
                        </button>
                    </form>
{{--                    <a href="{{route('posts.destroy',[$userId, $post->id])}}" class="btn-link ml-1"> <i class="fas fa-trash"></i>--}}
                    </a>
                </td>
            </tr>
        @endforeach

        </tbody>
    </table>

@endsection

resources/views/posts/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="col-12 mb-4">
                <div class="card mb-4 box-shadow ">
                        <div class="text-center">
                            <img class=" img-fluid  " src="{{$post->img_path}}" alt="Thumbnail [100%x225]"  width="400">

                        </div>
                    <div class="card-body">
                        <div class="card-header">
                            {{$post->name}}
                        </div>
                        <div class="card-text  mt-4">
                            <div class="h3 pl-4">
                                Post info:
                            </div>
                            <p class="pl-4">
                                {{$post->description}}
                            </p>

                        </div>

                        @auth
                            <hr>
                        <div >
                            <div class="mesgs mt-5">
                                <div class="msg_history">
                                    @foreach($post->comments as $comment)
                                        @if($comment->user_id == auth()->id())
                                            <div class="outgoing_msg">
                                                <div class="sent_msg">
                                                    <p>{{$comment->text}}</p>
                                                    <span
                                                        class="time_date"> {{$comment->created_at->diffForHumans()}}</span>
                                                </div>
                                            </div>

                                        @else
                                            <div class="incoming_msg">
                                                <div>{{$comment->comentor->name}}</div>
                                                <div class="incoming_msg_img"><img
                                                        src="https://ptetutorials.com/images/user-profile.png"
                                                        class="img-fluid"></div>
                                                <div class="received_msg">
                                                    <div class="received_withd_msg">
                                                        <p>{{$comment->text}}</p>
                                                        <span
                                                            class="time_date"> {{$comment->created_at->diffForHumans()}}</span>
                                                    </div>
                                                </div>
                                            </div>
                                        @endif
                                    @endforeach


                                </div>

                            </div>

                            <div class="h4 mt-4"> Write comment </div>
                            <form method="POST"
                                  action="{{route('comments.store', ['id' => auth()->id(), 'post' => $post->id])}}"
                                  class="comment-form"
                            >
                               @csrf
                                <div class="input-group">
                                    <input type="text" name="text" class="form-control " placeholder="Comment" aria-label="Recipient's username" aria-describedby="basic-addon2">
                                    <div class="input-group-append">
                                        <button class="btn btn-outline-primary" type="submit">Send</button>
                                    </div>
                                </div>

                            </form>
                        </div>
                        @endauth
                    </div>
                </div>
    </div>

@endsection

@push('scripts')
    <script  defer src="{{asset('js/post.js')}}"></script>
@endpush